replicaCount: 2

image:
  repository: 836809165836.dkr.ecr.us-west-2.amazonaws.com/final-project-ecr
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  DB_HOST: final-project-db.chgiqqick2qg.us-west-2.rds.amazonaws.com
  DB_PORT: "5432"
  POSTGRES_DB: django
  POSTGRES_USER: dbadmin
  DEBUG: "True"
  ALLOWED_HOSTS: "*"

secrets:
  POSTGRES_PASSWORD: ChangeMeDbPassword123!
  SECRET_KEY: django-insecure-change-me-in-production

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
