apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .Values.app.repoURL }}
